name: hello

on:
  push:
  repository_dispatch:
  schedule:
    - cron: "*/10 * * * *"
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: date
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          date > out
      - name: Release
        uses: fnkr/github-action-ghr@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_PATH: out
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
# vim: tabstop=2 shiftwidth=2 expandtab
