name: hello

on:
  push:
  repository_dispatch:
  schedule:
    - cron: "*/10 * * * *"
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: date
        run: |
          date > out
      - uses: actions/setup-go@v1
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          go get -u github.com/tcnksm/ghr
          $GOPATH/bin/ghr nightly out
# vim: tabstop=2 shiftwidth=2 expandtab
