name: hello

on:
  push:
  repository_dispatch:
  schedule:
    - cron: "*/10 * * * *"
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: date
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          date
          pwd
          ls
          cd ..
          pwd
          ls
          cd ..
          pwd
          ls
          uname -a
# vim: tabstop=2 shiftwidth=2 expandtab
