name: hello

on:
  push:
  repository_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: apt
        run: |
          sudo apt update
          sudo apt install -y ninja-build gettext libtool libtool-bin autoconf automake cmake g++ pkg-config unzip curl git

      - name: Set up Go 1.12
        uses: actions/setup-go@v1
        with:
          version: 1.12
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@master

      - name: build neovim
        run: |
          git clone https://github.com/neovim/neovim -b nightly
          cd neovim
          sed -e 's;^set(LIBVTERM_URL.*$;set(LIBVTERM_URL https://github.com/nat-chan/libvterm-0.1.2-DRCS-SIXEl/archive/3884ebe4e5c02f078754115aa5ceac0b83bdc16a.tar.gz);' \
              -e 's;^set(LIBVTERM_SHA256.*$;set(LIBVTERM_SHA256 c5166abbb81d1aeb8c74229fc46982433d3932223d338e8f7e6fcc4ff17e5473);' -i ./third-party/CMakeLists.txt
          make appimage
          cd ..

      - name: Release
        env:
          GO111MODULE: on
          GOPATH: /home/runner/work/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          go get -u github.com/tcnksm/ghr
          $GOPATH/bin/ghr nightly neovim/build/bin/nvim.appimage
# vim: tabstop=2 shiftwidth=2 expandtab
